Resources:
  Method1Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Sub ${self:service}-${self:provider.stage}-s493FinalProject
      Action: 'lambda:InvokeFunction'
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':quc406za77/*/*/*'
      Principal: apigateway.amazonaws.com