Resources:
  GatewayTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:service}-${self:provider.stage}-data
      AttributeDefinitions:
        - AttributeName: courses
          AttributeType: S
      KeySchema:
        - AttributeName: courses
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5