service: cs-493-final-project

frameworkVersion: '3'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    packager: "npm"
    includeModules: true

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2
  stage: main
  
  stackTags:
    Created By: Danielle Puga and Ryan Earl
  logs:
    restApi:
      format: >-
        { "requestId":"$context.requestId", "ip": "$context.identity.sourceIp", 
        "userId":"$context.authorizer.userId", "user":"$context.authorizer.user", 
        "store":"$context.authorizer.storeNumber", "requestTime":"$context.requestTime", 
        "httpMethod":"$context.httpMethod", "resourcePath":"$context.resourcePath", 
        "status":"$context.status", "protocol":"$context.protocol", "responseLength":"$context.responseLength" }
  environment:
    region: ${self:provider.region}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: !Sub arn:aws:lambda:${self:provider.region}:${AWS::AccountId}:function:${self:service}-*
    - Effect: "Allow"
      Action:
        - "dynamodb:Scan"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
      Resource: !Sub arn:aws:dynamodb:${self:provider.region}:${AWS::AccountId}:table/${self:service}-*
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource:
        - !Sub arn:aws:secretsmanager:${self:provider.region}:${AWS::AccountId}:secret:${self:service}-*
    - Effect: "Allow"
      Action:
        - "cognito-idp:AdminInitiateAuth"
        - "cognito-idp:ListUsers"
        - "cognito-idp:AdminConfirmSignUp"
        - "cognito-idp:adminAddUserToGroup"
      Resource: !Sub arn:aws:cognito-idp:${self:provider.region}:${AWS::AccountId}:userpool/${self:provider.region}_IoBo5jDL6
    
functions:
  - ${file(cloudformation/functions.yml)}

resources:
  - ${file(cloudformation/dynamodb.yml)}
  - ${file(cloudformation/apiGateway.yml)}

plugins:
  - serverless-webpack
  - serverless-plugin-resource-tagging

package:
  individually: true
  exclude:
    - buildspecs/**